package.json, src/components/account/preferences.tsx, src/hooks/use-color-scheme.ts, src/pages/_app.tsx, yarn.lock
=> Fixed dark mode flicker

src/components/gig/card.tsx, src/components/gig/datebox.tsx, src/components/gig/info.module.css, src/pages/gig/[id]/index.tsx
Made datebox show month, and made description always show
=> Redesign gig card

src/components/gig/info.module.css, src/components/signup-list/entry.tsx, src/components/signup-list/index.tsx, src/pages/gig/[id]/index.tsx
- Added a switch to move between user and admin view
- Added newlines between instruments in user view
- Fixed the zoomout issue in admin view
=> Reorganize signup page

src/components/statistics-table.tsx, src/pages/stats/[paramYear]/index.tsx, src/pages/stats/for/nerds/index.tsx, src/server/trpc/router/stats.ts
WIP
Also some small fixes to the stats page.
=> More stats!

src/components/account/stats.tsx, src/components/statistics-table.tsx, src/pages/stats/[paramYear]/index.tsx, src/server/trpc/router/rehearsal.ts, src/server/trpc/router/stats.ts
Rewrote stats query to take start and end date, and added custom interval to stats page.
=> Custom stats interval

package.json, src/hooks/use-color-scheme.ts, src/pages/_app.tsx, src/server/trpc/router/corps.ts, src/utils/cookie-parser.ts
First render has saved theme, and bug on downloaded "bookmark" as app on phones fixed aswell
Closes #94
=> Dark mode now fixed

src/hooks/use-color-scheme.ts, src/pages/_app.tsx, src/server/trpc/router/corps.ts
Should now work cookies are saved trough server and secure, fixed small issue with getInitalProps in _app returning unnecessary amount of undefined
Closes #110
=> Dark mode fixed

src/components/quote/form.tsx, src/components/quote/index.tsx, src/pages/quotes/[id]/index.tsx, src/pages/quotes/index.tsx, src/server/trpc/router/quote.ts
* Form for new quotes is now at the top of the page
* Quotes are now grouped by day they were written
* Quotes now display author and time
=> Reorganized quotes

src/server/trpc/router/stats.ts
Reliability is now based on the average amount of time between your initial signup and your latest change to your signup status.
=> Changed reliability query

src/components/signup-list/index.tsx
Added text about how many instruments are missing from gigs for full setting
=> Full setting

src/components/statistics-table.tsx
Stats now sort by attendence percentage, and now show cutoff for 75% and 50%
=> Fix sorting of stats

src/components/statistics-table.tsx
Stats now sorts secondarily by points
=> Fixed stats sorting

src/components/statistics-table.tsx
=> Fixed sorting for real

prisma/schema.prisma, src/pages/admin/rehearsal/index.tsx, src/server/trpc/router/gig.ts, src/utils/date.ts
updatedAt field in Signup now doesn't update when updating attendence, and rehearsals now show correctly and has createdAt and updatedAt fields
=> Misc date fixes

src/components/account/stats.tsx, src/components/rehearsal/stats.tsx, src/components/statistics-table.tsx, src/server/trpc/router/stats.ts
Attendence is now calculated as gigsAttended / totalNonPositiveGigs for any time interval
=> New attendence calculation

src/components/statistics-table.tsx
Removed fjång divider as there's no clear system for how it works yet
=> Removed fjång divider

src/components/account/preferences.tsx, src/components/gig/menu.tsx, src/components/signup-list/food-prefs.tsx, src/pages/admin/gig/[id]/info.tsx, src/server/trpc/router/corps.ts, src/server/trpc/router/gig.ts
Food prefs page now shows gig checkboxes, and drinksAlcohol was removed (use checkboxes instead)
=> Updated food prefs

src/components/signup-list/index.tsx, src/server/trpc/router/gig.ts, src/utils/permission.ts
manageAttendance is meant to be for people that can register attendance on gigs
=> Added manageAttendance as Permission

src/app/account/preferences.tsx, src/app/gigs/export-calendar.tsx, src/app/gigs/page.tsx, src/components/input/copy-to-clipboard.tsx, src/components/tooltip.tsx, src/server/trpc/router/gig.ts
The getBaseUrl() function returns empty string for me, but apart from that I have tested it and it works both locally and on google calendar.
=> Export gig calendar

src/app/about/page.tsx, src/components/gig/card.tsx, src/components/gig/signup-box.tsx
=> Remove maybe as an option on gigs with signupEnd

src/server/trpc/router/streck.ts
=> Added Summary sheet to exported strecklists

src/app/admin/streck/download.tsx, src/components/corps/display.tsx, src/components/signup-list/index.tsx, src/server/trpc/router/gig.ts, src/server/trpc/router/streck.ts, src/utils/corps.ts
=> Now displays ballet number at website and empty strecklist if corps doesn't have a corps number

src/app/account/page.tsx
=> Here you go Ella

src/app/account/page.tsx
Lets hope the actions work now
=> Properly display tne bNumer on account

src/server/trpc/router/stats.ts
Fix allTimeStreak to correctly handle corps first streak (before the first streak would not be added)
=> Fix allTimeStreak

src/app/home-page.tsx
=> Remove 'Kommande spelningar'
